language: ruby
rvm:
 - 3.0.1
cache:
  - bundler
  - yarn
services:
  - sqlite3
before_install:
  - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:schema:load
script:
  - bundle exec rake build
  - bundle exec rspec